# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 191a1caa937622ec5619e56a8c2a3ec59f23867f3617b1e187d219c8da1cdb45c56102a065b9c839d589bd456c0476d58e5ed27721cc8d1b49e28b39806c0e75

test:
  secret_key_base: 210ae1d3b397f2192a7d5f25b32acc159d507af38e16921839a1f8f7b64e0e0ff24e58fd7df2ef2db0b86a827573d5f4d11ffc4cd9eaf45562864341c0514a43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
